version: '2'
services:
  web:
    build: .
    container_name: sav_kosti_wedding
    ports:
    - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    links:
    - postgres
  postgres:
    image: postgres:alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
